version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  govet:
    enable:
      - shadow
  gosec:
    excludes:
      - G104

formatters:
  enable:
    - gofmt

